name: Status Update

on:
  workflow_dispatch: {}
  push:
    branches:
      - release
      - latest
  pull_request_target:
    types: [closed]
    branches:
      - release
      - latest

env:
  preferred-elixir: "1.12.2"
  preferred-otp: "24.0.3"

jobs:

  run:
    name: Status Update
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        elixir:
          - "1.12.2"
        otp:
          - "24.0.3"
        allow-failure: [false]

    if: github.event_name == 'push' || github.event.pull_request_target.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore Mix Cache
        id: mix-cache
        uses: actions/cache@v1
        with:
          path: deps
          key: cache-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Setup dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Report test coverage
        run: mix test.coverage.report

      # - name: Report documentation coverage
      #   run: mix inch.report
