name: Status Report

on:
  workflow_dispatch: {}
  push:
    branches:
      - release
      - latest
  pull_request_target:
    types: [closed]
    branches:
      - release
      - latest

env:
  # TODO: excoveralls fails with elixir 1.13;
  # for now we report coverage from 1.12.2.
  # see: https://github.com/parroty/excoveralls/issues/273
  preferred-elixir: "1.12.2"
  preferred-otp: "24.2.0"
  cache-version: 2
  MIX_ENV: test

concurrency:
  group: status-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Report Test Suite Status
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request_target.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Install erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.preferred-elixir }}
          otp-version: ${{ env.preferred-otp }}

      - name: Restore mix dependency installation cache
        id: mix-deps-get-cache
        uses: actions/cache@v1
        with:
          path: deps
          key: cache-${{ env.cache-version }}-${{ runner.os }}-${{ env.preferred-otp }}-${{ env.preferred-elixir }}-mix-deps-get-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install mix dependencies
        if: steps.mix-deps-get-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Restore mix dependency compilation cache
        id: mix-deps-compile-cache
        uses: actions/cache@v1
        with:
          path: _build
          key: cache-${{ env.cache-version }}-${{ runner.os }}-${{ env.preferred-otp }}-${{ env.preferred-elixir }}-mix-deps-compile-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Compile mix dependencies
        if: steps.mix-deps-compile-cache.outputs.cache-hit != 'true'
        run: mix deps.compile

      - name: Report test suite coverage
        run: mix test.coverage.report

      # - name: Report documentation coverage
      #   run: mix docs.coverage.report
