name: Test Suite

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - release
      - latest

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: suite-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest

    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        elixir:
          - "1.10.4"
          - "1.11.4"
          - "1.12.2"
        otp:
          - "22.3.4"
          - "23.3.1"
          - "24.0.3"
        allow-failure: [false]
        include:
          # Extra permutations we require passing the build

          - elixir: "1.10.0"
            otp: "23.3.1"
            allow-failure: false

          # Technically unsupported combinations we allow to fail

          # too future
          - elixir: "1.10.0"
            otp: "23.3.1"
            allow-failure: true
          - elixir: "1.10.0"
            otp: "24.0.3"
            allow-failure: true

    steps:
      - uses: actions/checkout@v2

      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore Mix Cache
        id: mix-cache
        uses: actions/cache@v1
        with:
          path: deps
          key: cache-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Setup dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix install

      - name: Run test suite
        run: mix test

  lints:
    name: Linting
    runs-on: ubuntu-latest

    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        elixir:
          - "1.10.4"
          - "1.11.4"
          - "1.12.2"
        otp:
          - "22.3.4"
          - "23.3.1"
          - "24.0.3"
        allow-failure: [false]
        include:
          # Extra permutations we require passing the build

          - elixir: "1.10.0"
            otp: "23.3.1"
            allow-failure: false

          # Technically unsupported combinations we allow to fail

          # too future
          - elixir: "1.10.0"
            otp: "23.3.1"
            allow-failure: true
          - elixir: "1.10.0"
            otp: "24.0.3"
            allow-failure: true

    steps:
      - uses: actions/checkout@v2

      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore Mix Cache
        id: mix-cache
        uses: actions/cache@v1
        with:
          path: deps
          key: cache-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Setup dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix install

      - name: Run compilation linter
        run: mix lint.compile

  types:
    name: Typechecking
    runs-on: ubuntu-latest

    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        elixir:
          - "1.10.4"
          - "1.11.4"
          - "1.12.2"
        otp:
          - "22.3.4"
          - "23.3.1"
          - "24.0.3"
        allow-failure: [false]
        include:
          # Extra permutations we require passing the build

          - elixir: "1.10.0"
            otp: "23.3.1"
            allow-failure: false

          # Technically unsupported combinations we allow to fail

          # too future
          - elixir: "1.10.0"
            otp: "23.3.1"
            allow-failure: true
          - elixir: "1.10.0"
            otp: "24.0.3"
            allow-failure: true

    steps:
      - uses: actions/checkout@v2

      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore Mix Cache
        id: mix-cache
        uses: actions/cache@v1
        with:
          path: deps
          key: cache-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Setup dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix install

      - name: Retrieve PLT Cache
        id: plt-cache
        uses: actions/cache@v1
        with:
          path: /home/runner/.cache/dialyzer/plts
          key: cache-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Setup typechecking
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: mix typecheck.cache

      - name: Run typecheck tasks
        run: mix typecheck
