name: Test Status

on:
  workflow_dispatch: {}

  push:
    branches:
      - release
      - latest

env:
  # TODO: excoveralls fails with elixir 1.13;
  # for now we report coverage from 1.12.2.
  # see: https://github.com/parroty/excoveralls/issues/273
  preferred-elixir: "1.12.x"
  preferred-otp: "24.x"
  cache-version: 6
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: test-status-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Report Test Suite Status
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request_target.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Install erlang & Elixir
        id: beam-versions
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.preferred-elixir }}
          otp-version: ${{ env.preferred-otp }}

      - name: Restore mix dependency installation cache
        id: mix-deps-get-cache
        uses: actions/cache@v1
        with:
          path: deps
          key: cache-${{ env.cache-version }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-mix-deps-get-mix-lock-file-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install mix dependencies
        if: steps.mix-deps-get-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Restore mix dependency compilation cache
        id: mix-deps-compile-cache
        uses: actions/cache@v1
        with:
          path: _build
          key: cache-${{ env.cache-version }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-mix-deps-compile-mix-lock-file-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Compile mix dependencies
        if: steps.mix-deps-compile-cache.outputs.cache-hit != 'true'
        run: mix deps.compile

      - name: Report test suite coverage
        run: mix test.coverage.report

      # - name: Report documentation coverage
      #   run: mix docs.coverage.report
