name: Test Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Version to test releasing (no "v" prefix)
        required: true
        default: test

  pull_request:
    branches:
      - release

env:
  preferred-elixir: "1.13.x"
  preferred-otp: "25.x"
  default-release-version: "test-version-number"
  cache-version: 7
  commit-author-name: ${{ secrets.ACTIONS_COMMIT_AUTHOR_NAME }}
  commit-author-email: ${{ secrets.ACTIONS_COMMIT_AUTHOR_EMAIL }}
  MIX_ENV: test
  HEX_API_KEY: ${{ secrets.ACTIONS_HEX_API_KEY }}

concurrency:
  group: test-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perform-release-dry-run:
    name: Test Release Process
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install erlang & Elixir
        id: beam-versions
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.preferred-elixir }}
          otp-version: ${{ env.preferred-otp }}

      - name: Restore Mix Cache
        id: mix-cache
        uses: actions/cache@v2
        with:
          path: deps
          key: cache-${{ env.cache-version }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-mix-mix-lock-file-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Setup dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Update version number
        run: |
          echo '${{ github.event.input.release-version || env.default-release-version }}' > VERSION
          cat VERSION

      - name: Preview new version commit
        run: |
          git config --global user.name "${{ env.commit-author-name }}"
          git config --global user.email "${{ env.commit-author-email }}"

          git commit -am "Release v$(cat VERSION)" --dry-run

      - name: Preview new version tags
        run: |
          echo "v$(cat VERSION)"
          echo stable

      - name: Preview publishing release to hex.pm
        run: |
          mix release --dry-run
